#! /usr/bin/env bash

export TP7_ROOT=$HOME/iTHEPHY-TP7
export HEPMC_ROOT=$TP7_ROOT/SOFT/INSTALL/HepMC
export PYTHIA6_ROOT=$TP7_ROOT/SOFT/INSTALL/Pythia6
export PYTHIA8_ROOT=$TP7_ROOT/SOFT/INSTALL/Pythia8
export LHAPDF_ROOT=$TP7_ROOT/SOFT/INSTALL/LHAPDF
export AGILE_ROOT=$TP7_ROOT/SOFT/INSTALL/AGILe
export SACRIFICE_ROOT=$TP7_ROOT/SOFT/INSTALL/Sacrifice
export ROOT_ROOT=$TP7_ROOT/SOFT/INSTALL/ROOT
export DELPHES_ROOT=$TP7_ROOT/SOFT/INSTALL/Delphes

export PS1="[TP7env][\u@\h \W]\$ "

export DYLD_LIBRARY_PATH=$HEPMC_ROOT/lib:$PYTHIA6_ROOT/lib:$PYTHIA8_ROOT/lib:$LHAPDF_ROOT/lib:$AGILE_ROOT/lib:$SACRIFICE_ROOT/lib:$ROOT_ROOT/lib:$DELPHES_ROOT/lib:$DYLD_LIBRARY_PATH
export LD_LIBRARY_PATH=$HEPMC_ROOT/lib:$PYTHIA6_ROOT/lib:$PYTHIA8_ROOT/lib:$LHAPDF_ROOT/lib:$AGILE_ROOT/lib:$SACRIFICE_ROOT/lib:$ROOT_ROOT/lib:$DELPHES_ROOT/lib:$DYLD_LIBRARY_PATH
export PATH=$AGILE_ROOT/bin:$SACRIFICE_ROOT/bin:$ROOT_ROOT/bin:$DELPHES_ROOT/bin:$PATH
export PYTHONPATH=$PYTHONPATH:$AGILE_ROOT/lib/python2.7/site-packages/AGILe

export ROOTSYS=$ROOT_ROOT
export PYTHIA8=$PYTHIA8_ROOT
export PYTHIA8DATA=$PYTHIA8_ROOT/share/Pythia8/xmldoc
export AGILE_GEN_PATH=$PYTHIA6_ROOT:$LHAPDF_ROOT

bash --noprofile --norc
